version: "3.3"
services:
  nginx:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./src/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
    networks:
      default:
      api:
        aliases:
          - backend.local
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    volumes:
      - ./src/frontend/src:/usr/src/app/src
      - ./src/frontend/public:/usr/src/app/public
      - ./src/frontend/index.html:/usr/src/app/index.html
      - ./src/frontend/tsconfig.json:/usr/src/app/tsconfig.json
      - ./src/frontend/vite.config.js:/usr/src/app/vite.config.js
    networks:
      - default
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./src/backend:/usr/src/app
      - ./src/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
    networks:
      - api
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    user: "1000:1000"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - api
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "7070:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - api

networks:
  api:
  default: